# Generated by Django 5.0.7 on 2024-08-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_product_colors_alter_productcolor_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorimage',
            name='color_code',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
