# Generated by Django 5.0.7 on 2024-08-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_product_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorimage',
            name='price',
        ),
    ]
