# Generated by Django 5.0.7 on 2024-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
