# Generated by Django 5.0.7 on 2024-08-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
