# Generated by Django 5.0.7 on 2024-08-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin_app', '0003_remove_productcolorimage_color_code_and_more'),
        ('cart_app', '0004_remove_order_payment_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(blank=True, default=1, null=True)),
                ('size', models.CharField(blank=True, default='S', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.productcolorimage')),
            ],
        ),
    ]
