# Generated by Django 5.0.7 on 2024-08-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='money_withdrawn',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
