# Generated by Django 5.0.7 on 2024-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_remove_transaction_money_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
