# Generated by Django 5.0.7 on 2024-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0017_mymodel_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Payment Failed', 'Payment Failed'), ('Payment Successful', 'Payment Successful'), ('Returned', 'Returned'), ('On Progress', 'On Progress')], default='Pending', max_length=20),
        ),
    ]
