# Generated by Django 5.0.7 on 2024-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0023_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
