<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0024_alter_orderitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
=======
# Generated by Django 5.1.1 on 2024-09-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0024_alter_orderitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
>>>>>>> 3783df7acc39134f0af3078c2d97fc51276f95b9
